"""initial_schema

Revision ID: 001
Revises: 
"""
import sqlalchemy as sa

from alembic import op

revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('start_time_utc', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('local_date', sa.Text(), nullable=False),
    sa.Column('elapsed_s', sa.Integer(), nullable=True),
    sa.Column('moving_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.REAL(), nullable=True),
    sa.Column('elev_gain_m', sa.REAL(), nullable=True),
    sa.Column('elev_loss_m', sa.REAL(), nullable=True),
    sa.Column('avg_hr', sa.REAL(), nullable=True),
    sa.Column('max_hr', sa.REAL(), nullable=True),
    sa.Column('avg_cadence_spm', sa.REAL(), nullable=True),
    sa.Column('avg_power_w', sa.REAL(), nullable=True),
    sa.Column('calories_kcal', sa.Integer(), nullable=True),
    sa.Column('has_gps', sa.Boolean(), nullable=True),
    sa.Column('has_hr', sa.Boolean(), nullable=True),
    sa.Column('has_cadence', sa.Boolean(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=True),
    sa.Column('workout_type', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('excluded_from_stats', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('primary_source_id', sa.Integer(), nullable=True),
    sa.Column('stream_source_id', sa.Integer(), nullable=True),
    sa.Column('summary_polyline', sa.Text(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('upstream_deleted_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.CheckConstraint("sport_type IN ('run', 'trail_run', 'treadmill')", name='ck_activities_sport_type'),
    sa.CheckConstraint("workout_type IN ('easy', 'long', 'workout', 'race', 'other')", name='ck_activities_workout_type'),
    sa.CheckConstraint('distance_m >= 0', name='ck_activities_distance_m'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['primary_source_id'], ['source_records.id'], name='fk_activities_primary_source', use_alter=True),
    sa.ForeignKeyConstraint(['stream_source_id'], ['source_records.id'], name='fk_activities_stream_source', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index('ix_activities_distance_m', ['distance_m'], unique=False)
        batch_op.create_index('ix_activities_local_date', ['local_date'], unique=False)
        batch_op.create_index('ix_activities_sport_type_local_date', ['sport_type', 'local_date'], unique=False)
        batch_op.create_index('ix_activities_start_time_utc', ['start_time_utc'], unique=False)
        batch_op.create_index('ix_activities_workout_type', ['workout_type'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('progress_done', sa.Integer(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('not_before', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('started_at', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name='ck_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_status_not_before', ['status', 'not_before'], unique=False)

    op.create_table('provider_accounts',
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('athlete_id', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('sync_cursor', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.Text(), nullable=True),
    sa.Column('last_reconcile_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(collation='NOCASE'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_metrics',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('algo_version', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.Text(), nullable=False),
    sa.Column('zones_hash', sa.Text(), nullable=True),
    sa.Column('time_in_zones_s', sa.JSON(), nullable=True),
    sa.Column('efficiency_factor', sa.REAL(), nullable=True),
    sa.Column('pace_cv', sa.REAL(), nullable=True),
    sa.Column('is_steady', sa.Boolean(), nullable=True),
    sa.Column('decoupling_pct', sa.REAL(), nullable=True),
    sa.Column('trimp', sa.REAL(), nullable=True),
    sa.Column('gps_suspect', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('activity_tags',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id', 'tag_id')
    )
    op.create_table('best_efforts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.REAL(), nullable=False),
    sa.Column('elapsed_s', sa.Integer(), nullable=False),
    sa.Column('start_offset_s', sa.Integer(), nullable=True),
    sa.Column('algo_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'distance_m', name='uq_best_efforts_activity_distance')
    )
    with op.batch_alter_table('best_efforts', schema=None) as batch_op:
        batch_op.create_index('ix_best_efforts_distance_m_elapsed_s', ['distance_m', 'elapsed_s'], unique=False)

    op.create_table('laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('start_offset_s', sa.Integer(), nullable=True),
    sa.Column('elapsed_s', sa.Integer(), nullable=True),
    sa.Column('moving_s', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.REAL(), nullable=True),
    sa.Column('avg_speed_ms', sa.REAL(), nullable=True),
    sa.Column('avg_hr', sa.REAL(), nullable=True),
    sa.Column('max_hr', sa.REAL(), nullable=True),
    sa.Column('avg_cadence_spm', sa.REAL(), nullable=True),
    sa.Column('elev_gain_m', sa.REAL(), nullable=True),
    sa.CheckConstraint("kind IN ('device_lap', 'split_km')", name='ck_laps_kind'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'kind', 'idx', name='uq_laps_activity_kind_idx')
    )
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_summary', sa.JSON(), nullable=True),
    sa.Column('raw_detail', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('source_start_time_utc', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.Text(), nullable=True),
    sa.Column('mapper_version', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('strava', 'file_fit', 'file_gpx', 'file_tcx', 'apple_health')", name='ck_source_records_source'),
    sa.CheckConstraint("status IN ('pending', 'mapped', 'duplicate', 'skipped', 'error')", name='ck_source_records_status'),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_records_source_external_id')
    )
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.create_index('ix_source_records_activity_id', ['activity_id'], unique=False)
        batch_op.create_index('ix_source_records_status', ['status'], unique=False)

    op.create_table('streams',
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('n_points', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('codec_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_record_id')
    )
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streams_activity_id'), ['activity_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_streams_activity_id'))

    op.drop_table('streams')
    with op.batch_alter_table('source_records', schema=None) as batch_op:
        batch_op.drop_index('ix_source_records_status')
        batch_op.drop_index('ix_source_records_activity_id')

    op.drop_table('source_records')
    op.drop_table('laps')
    with op.batch_alter_table('best_efforts', schema=None) as batch_op:
        batch_op.drop_index('ix_best_efforts_distance_m_elapsed_s')

    op.drop_table('best_efforts')
    op.drop_table('activity_tags')
    op.drop_table('activity_metrics')
    op.drop_table('tags')
    op.drop_table('settings')
    op.drop_table('provider_accounts')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_not_before')

    op.drop_table('jobs')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index('ix_activities_workout_type')
        batch_op.drop_index('ix_activities_start_time_utc')
        batch_op.drop_index('ix_activities_sport_type_local_date')
        batch_op.drop_index('ix_activities_local_date')
        batch_op.drop_index('ix_activities_distance_m')

    op.drop_table('activities')
    # ### end Alembic commands ###
