import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, ApiError } from '../api/client'

// --- API shapes (app/api/ai.py) ---------------------------------------------
type Insight = { kind: 'observation' | 'interpretation' | 'hypothesis'; text: string; evidence: string }
type Analysis = { summary: string; insights: Insight[]; caveats: string[]; data_sufficiency: 'sufficient' | 'limited' | 'insufficient' }
type AiState = {
  enabled: boolean
  used_today: number
  daily_limit: number
  insufficient: string | null
  stale: boolean
  result: { model: string; created_at: string; analysis: Analysis } | null
}

const KIND: Record<Insight['kind'], string> = { observation: 'observed', interpretation: 'interpretation', hypothesis: 'hypothesis' }
const ERR: Record<string, string> = {
  not_configured: 'AI is not configured (OPENROUTER_API_KEY).',
  rate_limited: 'AI request limit reached. Try again later.',
  busy: 'An AI analysis is already running.',
}

function errorText(e: unknown): string {
  const d = e instanceof ApiError ? (e.detail as { code?: string; message?: string } | undefined) : undefined
  if (d?.code) return ERR[d.code] ?? d.message ?? 'AI analysis failed.'
  return 'AI analysis failed or timed out. Try again later.'
}

/** Cached AI analysis for one subject. Loading the page never calls the model: only the button does. */
export default function AiPanel({ path, body = {} }: { path: string; body?: object }) {
  const qc = useQueryClient()
  const key = ['ai', path, JSON.stringify(body)]
  const qs = new URLSearchParams(Object.entries(body).filter(([, v]) => v) as [string, string][])
  const state = useQuery({ queryKey: key, queryFn: () => api<AiState>(`${path}${qs.size ? `?${qs}` : ''}`) })
  const run = useMutation({
    mutationFn: () => api<AiState>(path, { method: 'POST', body: JSON.stringify(body) }),
    onSuccess: (d) => qc.setQueryData(key, d),
  })
  const s = state.data
  if (!s) return null
  const r = s.result
  const canRun = s.enabled && !s.insufficient && !run.isPending && (!r || s.stale)

  return (
    <section className="space-y-2">
      <h2 className="text-xs tracking-wide text-neutral-500 uppercase">
        AI analysis
        <abbr title="Generated by a language model from statistics computed by this app. It can be wrong." className="ml-1.5 text-[10px] normal-case no-underline">
          model
        </abbr>
      </h2>

      {r && (
        <div className={`max-w-3xl space-y-2 text-sm ${s.stale ? 'opacity-60' : ''}`}>
          <p className="text-neutral-200">{r.analysis.summary}</p>
          <ul className="space-y-1.5">
            {r.analysis.insights.map((i, n) => (
              <li key={n}>
                <span className="mr-1.5 text-xs text-neutral-500">{KIND[i.kind]}</span>
                <span className="text-neutral-300">{i.text}</span>
                {i.evidence && <span className="block text-xs text-neutral-500 tabular-nums">{i.evidence}</span>}
              </li>
            ))}
          </ul>
          {r.analysis.caveats.length > 0 && (
            <ul className="list-disc pl-4 text-xs text-neutral-500">
              {r.analysis.caveats.map((c, n) => <li key={n}>{c}</li>)}
            </ul>
          )}
          <p className="text-xs text-neutral-500">
            {r.analysis.data_sufficiency !== 'sufficient' && <span className="mr-2 text-neutral-400">Data: {r.analysis.data_sufficiency}.</span>}
            AI-generated ({r.model.split('/').pop()}) on {r.created_at.slice(0, 10)} from app-computed stats. Not medical advice.
            {s.stale && <span className="ml-2 text-neutral-400">Data changed since.</span>}
          </p>
        </div>
      )}

      <div className="flex flex-wrap items-center gap-3 text-sm">
        {(!r || s.stale) && (
          <button
            onClick={() => run.mutate()}
            disabled={!canRun}
            className="min-h-10 rounded border border-border bg-panel px-3 py-1 text-accent disabled:text-neutral-600 md:min-h-0"
          >
            {run.isPending ? 'Analyzing…' : r ? 'Re-analyze' : 'Analyze with AI'}
          </button>
        )}
        {run.isPending && <span className="text-xs text-neutral-500">can take up to a minute</span>}
        {s.insufficient && <span className="text-xs text-neutral-500">Not enough data: {s.insufficient}</span>}
        {!s.enabled && <span className="text-xs text-neutral-500">{ERR.not_configured}</span>}
        {run.isError && <span className="text-xs text-red-400">{errorText(run.error)}</span>}
        {s.enabled && (!r || s.stale) && (
          <span className="ml-auto text-xs text-neutral-600 tabular-nums" title="Requests sent to the AI provider today (local budget)">
            {s.used_today}/{s.daily_limit} today
          </span>
        )}
      </div>
    </section>
  )
}
